CU/Controllers/CreateFormController.cs
using CU.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CU.Services;

namespace CU.Controllers
{
    public class CreateFormController : BaseController
    {
        private readonly ILogger<CreateFormController> _logger;

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SearchResult()
        {
            return View();
        }

        public IActionResult PersonalInfo()
        {
            return View();
        }

        public IActionResult WorkandCourse()
        {
            return View();
        }

       

        public IActionResult Experience()
        {
            return View();
        }

        public IActionResult Article()
        {
            return View();
        }

        public IActionResult Etc()
        {
            return View();
        }
        public IActionResult Preview()
        {
            return View();
        }
        public IActionResult Validation()
        {
            return View();
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public JsonResult GetTitle(string type)
        {
            PersonalService serv = new PersonalService();
            List<TitleName> titleNames = serv.GetTitle(type);
            return Json(GetOk(titleNames));
        }

        [HttpGet]
        public JsonResult GetJobTitle(string type)
        {
            PersonalService serv = new PersonalService();
            List<JobTitle> jobTitles = serv.GetJobTitle(type);
            return Json(GetOk(jobTitles));
        }

        [HttpGet]
        public JsonResult GetCountry()
        {
            PersonalService serv = new PersonalService();
            List<Country> countries = serv.GetCountry();
            return Json(GetOk(countries));
        }

        [HttpGet]
        public JsonResult GetBank()
        {
            PersonalService serv = new PersonalService();
            List<BankInfo> bankinfo = serv.GetBank();
            return Json(GetOk(bankinfo));
        }

        [HttpGet]
        public JsonResult GetBankBranch(string bankcode)
        {
            PersonalService serv = new PersonalService();
            List<BankInfo> bankinfo = serv.GetBankBranch(bankcode);
            return Json(GetOk(bankinfo));
        }

        [HttpGet]
        public JsonResult GetCity(string contrycode)
        {
            PersonalService serv = new PersonalService();
            List<City> cities = serv.GetCity(contrycode);
            return Json(GetOk(cities));
        }

        [HttpGet]
        public JsonResult GetDistict(string citycode)
        {
            PersonalService serv = new PersonalService();
            List<District> district = serv.GetDistict(citycode);
            return Json(GetOk(district));
        }

        [HttpGet]
        public JsonResult GetSubDistict(string citycode, string districtcode)
        {
            PersonalService serv = new PersonalService();
            List<SubDistrict> subdistrict = serv.GetSubDistict(citycode, districtcode);
            return Json(GetOk(subdistrict));
        }
        
        [HttpGet]
        public JsonResult GetPostCode(string citycode, string districtcode, string subdistrictcode)
        {
            PersonalService serv = new PersonalService();
            string subdistrict = serv.GetPostCode(citycode, districtcode, subdistrictcode);
            return Json(GetOk(subdistrict));
        }
    }
}

CU/Views/CreateForm/Etc.cshtml
@{
    ViewData["Title"] = "Search Result";
}

<link rel="stylesheet" href="~/css/createform.css">
<link rel="stylesheet" href="~/css/home.css" />

<div class="container full-width-container  personal-info">
    <div class="content">
        <div class="flex-row row">
            <div class="col-md-4"><h4>แบบฟอร์มการขอแต่งตั้งอาจารย์พิเศษ</h4></div>
            <div class="flex-row document-status"><p>สถานะเอกสาร :</p><p class="margin-left-10">บันทึกร่าง</p></div>

        </div>
        <div class="progress-createform">
            <div class="flex-row">
                <div class="head">
                    <a href="@Url.Action("PersonalInfo", "CreateForm")">
                        <div class="flex-column">
                            <div class="circle selected">1</div>
                            <div class="selected-descrip">ข้อมูลส่วนบุคคล</div>
                        </div>
                    </a>
                </div>
                <div class="line selected"></div>
                <div class="head">
                    <a href="@Url.Action("WorkandCourse", "CreateForm")">
                        <div class="flex-column">
                            <div class="circle selected">2</div>
                            <div class="selected-descrip">งานและหลักสูตร</div>
                        </div>
                    </a>
                </div>
                <div class="line selected"></div>
                <div class="head">
                    <a href="@Url.Action("Education", "Education")">
                        <div class="flex-column">
                            <div class="circle selected">3</div>
                            <div class="selected-descrip">วุฒิการศึกษา</div>
                        </div>
                    </a>
                </div>
                <div class="line selected"></div>
                <div class="head">
                    <a href="@Url.Action("Experience", "CreateForm")">
                        <div class="flex-column">
                            <div class="circle selected">4</div>
                            <div class="selected-descrip">ประสบการณ์</div>
                        </div>
                    </a>
                </div>
                <div class="line selected"></div>
                <div class="head">
                    <a href="@Url.Action("Article", "CreateForm")">
                        <div class="flex-column">
                            <div class="circle selected">5</div>
                            <div class="selected-descrip">ผลงานวิชาการ</div>
                        </div>
                    </a>
                </div>
                <div class="line selected"></div>
                <div class="head">
                    <div class="flex-column">
                        <div class="circle selected">6</div>
                        <div class="selected-descrip">อื่นๆ</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form">
            <div class="flex-row ">
                <div class="head-square"></div>
                <div class="topic-square">เอกสารที่เกี่ยวข้อง</div>
                <a href="#"><div class="border-button ml-3 mb-1"><i class="fas fa-plus"></i>อัปโหลดไฟล์</div></a>
            </div>
            <div class="margin-top-10">
                <table class="styled-table">
                    <thead>
                        <tr>

                            <th>ประเภทเอกสาร</th>
                            <th>ชื่อเอกสาร</th>
                            <th></th>

                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>CV</td>
                            <td><i class="fas fa-paperclip margin-right-10"></i>CV.pdf</td>
                            <td class="flex-row table-icon">
                                <div class="delete-btn"><i class="fa fa-trash"></i></div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="flex-row ">
                <div class="head-square"></div>
                <div class="topic-square">อื่นๆ</div>
            </div>
            <div class="flex-column width-100-percent">
                <div class="form-item margin-top-10">
                    <form class="form-style-8">
                        <p>ระบุเหตุผลกรณีเสนอขอแต่งตั้งนอกระยะเวลาที่กำหนด</p>
                        <input style="width:100%" type="text" name="" placeholder="" />
                    </form>
                </div>
            </div>
            <div class="btn-group flex-row mt-5 mb-5">
                <a href="@Url.Action("Article", "CreateForm")"><div class="secondary-btn"><p class="text-center">ย้อนกลับ</p></div></a>
                <a href="@Url.Action("Preview", "CreateForm")"><div class="secondary-btn"><p class="text-center">แสดงรายละเอียดคำขอ</p></div></a>
                <a href="@Url.Action("Validation", "CreateForm")"><div class="primary-btn"><p class="text-center">ตรวจสอบ</p></div></a>
                <a href="@Url.Action("", "")"><div class="primary-btn" style="display:none;"><p class="text-center">ถัดไป</p></div></a>
            </div>
        </div>
    </div>
</div>

CU/Views/CreateForm/Index.cshtml
@{
    ViewData["Title"] = "Create Form";
}

<link rel="stylesheet" href="~/css/createform.css">
<link rel="stylesheet" href="~/css/home.css" />
<link rel="stylesheet" href="~/lib/dtpickr/datepicker.css" />
<style>
    body {
        background-image: url("../../Image/background.png") !important;
    }
    
</style>
<div class="container full-width-container  createform">
    <div class="box p-4 pl-5">
        <div class="content">
            <div class="form-item flex-row">
                <p class="head-field">ประเภท</p>

                <form id="myForm" class="flex-row">
                    <input class="margin-right-10" type="radio" name="radioName" value="1" checked /><label class="margin-right-30">ไทย</label>  <br />
                    <input class="margin-right-10" type="radio" name="radioName" value="2" /><label> ชาวต่างประเทศ</label>  <br />
                </form>

                @*<label>
                <input type="radio" name="radioName" value="thai" checked />
                <span>ไทย</span>
            </label>
            <label>
                <input type="radio" name="radioName" value="inter" />
                <span>ต่างประเทศ</span>
            </label>*@
            </div>
            <div class="inter">
                <div class="form-item">
                    <form class="form-style-8">
                        <p><span style="color:red;">* </span>เลขที่หนังสือเดินทาง</p>
                        <input type="text" name="passportid" placeholder="" />
                    </form>
                </div>
                <div class="form-item">
                    <form class="form-style-8">
                        <p><span style="color:red;">* </span>ชื่อ</p>
                        <input type="text" name="name" placeholder="" />
                    </form>
                </div>
                <div class="form-item">
                    <form class="form-style-8">
                        <p><span style="color:red;">* </span>นามสกุล</p>
                        <input type="text" name="lastname" placeholder="" />
                    </form>
                </div>
                <div class="form-item">
                    <form class="form-style-8">
                        <p><span style="color:red;">* </span>วันเดือนปีเกิด</p>
                        <input type="text" name="txtbirthdate" id="txtbirthdate" placeholder="DD/MM/YYYY" />
                    </form>
                </div>
            </div>
            <div class="thai">
                <div class="form-item">
                    <form class="form-style-8">
                        <p><span style="color:red;">* </span>รหัสบัตรประชาชน</p>
                        <input type="text" name="personalid" placeholder="" />
                    </form>
                </div>
                </div>
            <div class="flex-row mt-4">
                <a href="@Url.Action("Index", "Menu")"><div class="back-btn mr-3"><i class="fas fa-arrow-left"></i></div></a>
                <a href="@Url.Action("SearchResult", "CreateForm")"><div class="btn">ตรวจสอบข้อมูล</div></a>
            </div>
                
            </div>
        </div>
</div>


<script src="~/lib/dtpickr/bootstrap-datepicker.js"></script>

<script>
    $(".thai").show();
    $(".inter").hide();

    $('#myForm input').on('change', function () {
        if ($('input[name=radioName]:checked', '#myForm').val() == 1) {
            $(".thai").show();
            $(".inter").hide();
        }
        else {
            $(".inter").show();
            $(".thai").hide();
        }
    });

    $(function () {
        $('#txtbirthdate').datepicker({
            language: 'en',
            format: 'dd/mm/yyyy',
        });

    });
    

</script>

CU/Views/CreateForm/SearchResult.cshtml
@{
    ViewData["Title"] = "Search Result";
}

<link rel="stylesheet" href="~/css/createform.css">
<link rel="stylesheet" href="~/css/home.css" />

<div class="container full-width-container" style="background:white;">
    <div class="content">
        <a href="@Url.Action("PersonalInfo", "CreateForm")">
            <div class="round-icon-btn"><i class="fas fa-plus"></i><p>สร้างรายการใหม่</p></div>
        </a>
        <p class="head-text">ผลการตรวจสอบ</p>
        <div class="mb-2">
            <div class="flex-row">
                <p class="head-field">ประเภท</p>
                <p class="field">: ช่าวต่างชาติ</p>
            </div>
            <div class="flex-row">
                <p class="head-field">เลขที่หนังสือเดินทาง</p>
                <p class="field">: 1234567890</p>
            </div>
            <div class="flex-row">
                <p class="head-field">วันเดือนปีเกิด</p>
                <p class="field">: 28/6/2520</p>
            </div>
            <div class="flex-row">
                <p class="head-field">ชื่อ-นามสกุล</p>
                <p class="field">: อเล็กซานเดอร์ แม็ค</p>
            </div>
        </div>


        <table class="styled-table">
            <thead>
                <tr>
                    <th></th>
                    <th>เลขที่หนังสือเดินทาง</th>
                    <th>วันเดือนปีเกิด</th>
                    <th>ชื่อ-นามสกุล</th>

                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><input type="radio" id="html" name="fav_language" value="HTML"></td>
                    <td>1234567890</td>
                    <td>28/06/2520</td>
                    <td>อเล็กซานเดอร์ แม็คเคอเรล</td>
                </tr>
                <tr class="active-row">
                    <td><input type="radio" id="html" name="fav_language" value="HTML"></td>
                    <td>1234567888</td>
                    <td>28/06/2520</td>
                    <td>อเล็กซ์ แม็คอินทอช</td>
                </tr>
                <tr class="active-row">
                    <td><input type="radio" id="html" name="fav_language" value="HTML"></td>
                    <td>1234567777</td>
                    <td>28/06/2520</td>
                    <td>เล็ก แม็ค</td>
                </tr>
            </tbody>
        </table>

        <div class="btn-group flex-row mt-3">
            <a href="@Url.Action("Index", "CreateForm")"><div class="secondary-btn"><p class="text-center">ย้อนกลับ</p></div></a>
            <a href="@Url.Action("PersonalInfo", "CreateForm")"><div class="primary-btn"><p class="text-center">เลือก</p></div></a>
        </div>


    </div>

</div>

CU/Views/CreateForm/UploadExcel.cshtml
@{
    ViewData["Title"] = "UploadExcel";
}

<link rel="stylesheet" href="~/css/createform.css">
<link rel="stylesheet" href="~/css/home.css" />
<link rel="stylesheet" href="~/css/global.css" />
<style>
    body {
        background-image: url(../../Image/background.png) !important;
        background-repeat: no-repeat, no-repeat;
        display: flex;
        flex-direction: column;
    }
</style>

<div class="container full-width-container upload-excel">
    <div class="content">
        <div class="col-md-12 col-sm-12 col-xs-12 type-group ">
            <p class="head-text mb-3">นำเข้าข้อมูลผู้ใช้งาน</p>
            <div>
                <p class="mb-3 mr-2 font-18">นำเข้าข้อมูลจากไฟล์</p>
                <div class="flex-row row mb-2 ">
                    <div class="col-md-2">
                        <label for="namefile"><span style="color:red;">*</span>ไฟล์รายชื่อผู้ใช้</label>
                    </div>
                    <div class="col-md-2">
                        <input type="file" id="namefile" name="namefile">
                    </div>
                </div>
                <div class="flex-row row mb-5 mt-5">
                    <div class="col-md-2">
                        <label for="imagefile">นำเข้าข้อมูลรุปภาพ</label>
                    </div>
                    <div class="col-md-2">
                        <input type="file" id="imagefile" name="imagefile">
                    </div>
                </div>
                <div class="btn-group flex-row">
                    <a href="@Url.Action("Index", "Menu")"><div class="secondary-btn"><p class="text-center">ย้อนกลับ</p></div></a>
                    <a href=""><div class="primary-btn"><p class="text-center">ตรวจสอบการนำเข้า</p></div></a>
                </div>
            </div>
        </div>
        <!--
        <div class="pink-btn btn"><a data-toggle="modal" data-target=".modal-setting"><p style="color: white; ">ตรวจสอบการนำเข้า</p></a></div>

    -->
    </div>
</div>

CU/Views/CreateForm/Validation.cshtml
@{
    ViewData["Title"] = "Search Result";
}

<link rel="stylesheet" href="~/css/createform.css">
<link rel="stylesheet" href="~/css/home.css" />

<div class="container full-width-container  personal-info validation">
    <div class="content">
        <div class="flex-row row">
            <div class="col-md-4"><h4>แบบฟอร์มการขอแต่งตั้งอาจารย์พิเศษ</h4></div>
            <div class="flex-row document-status"><p>สถานะเอกสาร :</p><p class="margin-left-10">บันทึกร่าง</p></div>

        </div>

        <div class="mt-2">
            <div class="flex-row ">
                <div class="head-square"></div>
                <div class="topic-square">ตรวจสอบเกณฑ์มาตรฐานหลักสูตร</div>
            </div>
            <div class="flex-row float-left mt-4">
                <p>
                    เป็น <span class="mx-2 pink-bold ">ผู้เชี่ยวชาญเฉพาะ</span>
                    ตาม มติครั้งที่<span class="mx-2 pink-bold "> 1/2560</span> ลงวันที่<span class="mx-2 pink-bold ">02/02/2560</span> <br />
                    มีผลตั้งแต่<span class="mx-2 pink-bold ">01/03/2560</span>ถึง<span class="mx-2 pink-bold ">01/03/2565</span>
                </p> 
            </div>
            <div class="mt-2">
                <table class="styled-table">
                    <thead>
                        <tr>

                            <th>หลักสูตร</th>
                            <th>เกณฑ์มาตรฐานหลักสูตร</th>
                            <th>ผ่านเกณฑ์/ไม่ผ่านเกณฑ์</th>
                            <th>หมายเหตุ</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>หลักสูตรแพทยศาสตร์บัณฑิต</td>
                            <td>ปี 2558</td>
                            <td class="pass"><i style="color: #22cb84;" class="fas fa-check-circle"></i></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>หลักสูตรประกาศนียบัตรบัณฑิตชั้นสูงทางวิทยาศาสตร์การแพทย์คลินิก</td>
                            <td>ปี 2558</td>
                            <td class="pass"><i style="color: #c23f2d;" class="fas fa-times-circle"></i></td>
                            <td>ผู้เชี่ยวชาญเฉพาะ</td>
                        </tr>
                        <tr>
                            <td>หลักสูตรประกาศนียบัตรบัณฑิตชั้นสูงทางวิทยาศาสตร์การแพทย์คลินิก</td>
                            <td>ปี 2548</td>
                            <td class="pass"><i style="color: #22cb84;" class="fas fa-check-circle"></i></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
            <div class="btn-group flex-row mt-5 mb-5">
                <a href="@Url.Action("Etc", "CreateForm")"><div class="secondary-btn"><p class="text-center">ย้อนกลับ</p></div></a>
                <a href="@Url.Action("", "")"><div class="green-btn flex-row"><i class="fas fa-long-arrow-alt-right"></i><p class="text-center">ส่งเสนอขอแต่งตั้ง</p></div></a>
                <a href="@Url.Action("", "")"><div class="red-btn flex-row"><i class="fas fa-times"></i><p class="text-center">ยกเลิกเอกสาร</p></div></a>
            </div>
        </div>
    </div>
</div>