CU/Controllers/SchedulerController.cs
using CU.Job;
using CU.Models;
using CU.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CU.Controllers
{
    public class SchedulerController : BaseController
    {
        [Authorize(Policy = Constants.PolicyName.JobPage)]
        [Route("[controller]")]
        public IActionResult Index()
        {
            CronJobService cronJobService = new CronJobService();

            ViewBag.Jobs = cronJobService.GetAll();
            ViewBag.showPopUp = "false";
            return View(new JobDisplay());
        }

        [Authorize(Policy = Constants.PolicyName.JobPage)]
        [Route("[controller]/GetById/{Id}")]
        public IActionResult GetById(string Id)
        {
            CronJobService cronJobService = new CronJobService();

            return PartialView("Detail", cronJobService.GetById(Convert.ToInt32(UrlDecrypt(Id))));
        }

        [Authorize(Policy = Constants.PolicyName.JobPage)]
        [Route("[controller]/UpdateSchedule")]
        [HttpPost]
        public IActionResult UpdateSchedule(string JobID ,JobDisplay jobDisplay)
        {
            jobDisplay.Id = Convert.ToInt32(UrlDecrypt(JobID));
            CronJobService cronJobService = new CronJobService();
            if(cronJobService.Update(jobDisplay, out string Msg))
            {
                ShowSuccessModal(Msg);
                return RedirectToAction("Index");
            }
            else
            {
                ShowFailureModal(Msg);
            }

            ViewBag.Jobs = cronJobService.GetAll();
            ViewBag.showPopUp = "true";
            return View("Index", jobDisplay);
        }

        [Route("[controller]/Jobs/Run")]
        [HttpPost]
        public IActionResult RunScheduler()
        {
            if (Environment.GetEnvironmentVariable("JOBS_ENABLE") == "0")
            {
                System.Threading.Tasks.Task.Run(() =>
                {
                    MasterJob masterJob = new MasterJob();
                    masterJob.ExceuteJob();
                });
                return GetOk();
            }

            return GetError();
        }
    }
}

CU/Views/Scheduler/Detail.cshtml
@model CU.Models.JobDisplay

@using (Html.BeginForm("UpdateSchedule", "Scheduler", FormMethod.Post))
{
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header" style="padding:12px 15px;">
                <h4 class="modal-title">ตั้งค่า Job Schedule</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <img src="~/Image/icon/cross-g.png" class="img-icon" />
                </button>
            </div>
            <div class="modal-body">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    @Html.Hidden("JobID", CU.Utilities.CryptoHelpers.UrlEncrypt(Model.Id.ToString()))
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Job name</label>
                                @Html.TextBoxFor(m => m.JobName, new { @class = "form-control", @readonly = "readonly", @id = "" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Minutes <span class="text-red-b">*</span></label>
                                @Html.TextBoxFor(m => m.Minutes, new { @class = "form-control", required = "required", maxlength = "10", autocomplete = "off", @id = "" })
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Hours <span class="text-red-b">*</span></label>
                                @Html.TextBoxFor(m => m.Hours, new { @class = "form-control required-auth", maxlength = "10", autocomplete = "off", @id = "" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Day of month <span class="text-red-b">*</span></label>
                                @Html.TextBoxFor(m => m.DayofMonth, new { @class = "form-control", required = "required", maxlength = "10", autocomplete = "off", @id = "" })
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Month <span class="text-red-b">*</span></label>
                                @Html.TextBoxFor(m => m.Month, new { @class = "form-control", required = "required", maxlength = "10", autocomplete = "off", @id = "" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Day of Week <span class="text-red-b">*</span></label>
                                @Html.TextBoxFor(m => m.DayofWeek, new { @class = "form-control", required = "required", maxlength = "10", autocomplete = "off", @id = "" })
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="col-sm-12 checkbox-group">
                                @Html.CheckBoxFor(m => m.JobEnable, new { @class = "form-check-input", @id = "JobEnable" })
                                <label for="JobEnable" class="check-custom">Enable</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-md-12 col-sm-12 col-xs-12 p-0">
                    <div class="form-group" style="margin-bottom:5px;">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12 p-0 text-center">
                                <button type="submit" class="btn btn-main" style="margin-top:5px;">
                                    บันทึก
                                </button>
                                <button type="button" class="btn btn-gray" style="margin-top:5px;" data-dismiss="modal" aria-label="Close">
                                    ยกเลิก
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

CU/Views/Scheduler/Index.cshtml
@model CU.Models.JobDisplay
@{
    ViewData["Title"] = "Job Scheduler";
}
@*@{ Layout = "_AuthorizeLayout"; }*@
    <link rel="stylesheet" href="~/css/account.css" />
    <link rel="stylesheet" href="~/css/global.css" />
    <link rel="stylesheet" href="~/css/home.css" />

    <div class="container">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="row flex-row">
                <div class="col-md-12 col-sm-12 col-xs-12 text-center head flex-row">
                    <h1 class="mt-5">Job Scheduler</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="col-md-12 col-sm-12 col-xs-12 p-0 btn-setting row flex-row">
                        <div class="btn-group mb-3">
                            <a href="@Url.Action("Index", "Admin")" class="secondary-btn">ย้อนกลับ</a>
                            @*<a class="primary-btn" data-toggle="modal" data-target=".modal-setting"><span><img src="~/Image/icon/gear-w.png" class="img-icon">&nbsp;ตั้งค่า</span></a>
*@
                    </div>
                </div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12 form-frame csvset-page">
        <!--csv schedule config-->

        <div class="col-md-12 col-sm-12 col-xs-12 search-result">
            <div class="row">
                <div class="table-frame-block">
                    <table cellpadding="0" cellspacing="0">
                        <thead class="topic">
                            <tr>
                                <th class="topic-jobname">
                                    Job Name
                                </th>
                                <th class="topic-cronjob">
                                    Cron Expression
                                </th>
                                <th class="topic-enable">
                                    Enable
                                </th>
                                <th class="topic-status">
                                    Status
                                </th>
                                <th class="topic-tools">
                                    &nbsp;
                                </th>
                            </tr>
                        </thead>
                        <thead class="topic topic-mobile">
                            <tr>
                                <th class="text-center">
                                    รายการ
                                </th>
                            </tr>
                        </thead>
                        <tbody class="detail detail-mobile">
                            @foreach (var job in ViewBag.Jobs)
                            {
                                <tr>
                                    <td class="detail-jobname">
                                        <span class="text-topic">Job Name:</span> @job.JobName
                                    </td>
                                    <td class="detail-cronjob">
                                        @job.GetCronEx()
                                    </td>
                                    <td class="detail-enable">
                                        <span class="text-topic">Enable:</span>
                                        @if (job.JobEnable)
                                        {
                                            <img src="/Image/icon/tick-color.png" style="height:23px;">
                                        }
                                        else
                                        {
                                            <img src="/Image/icon/cross-color.png" style="height:23px;">
                                        }
                                    </td>
                                    <td class="detail-status">
                                        <span class="text-topic">Status:</span> @job.Status
                                    </td>
                                    <td class="detail-tools">
                                        <a class="btn-tools edit" data-id="@CU.Utilities.CryptoHelpers.UrlEncrypt(job.Id.ToString())"><img src="/Image/icon/edit-w.png" class="img-icon"></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
            </div>
        </div>
    </div>
</div>

@*--------Modal Config---------*@
<div id="ConfigModal" class="modal fade modal-setting" tabindex="-1" role="dialog" aria-labelledby="myModalLabel10" aria-hidden="true">
    @using (Html.BeginForm("UpdateSchedule", "Scheduler", FormMethod.Post))
    {
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header" style="padding:12px 15px;">
                    <h4 class="modal-title">ตั้งค่า Job Schedule</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <img src="~/Image/icon/cross-g.png" class="img-icon" />
                    </button>
                </div>
                <div class="modal-body">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        @Html.Hidden("JobID", CU.Utilities.CryptoHelpers.UrlEncrypt(Model.Id.ToString()))
                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                <div class="form-group">
                                    <label>Job name</label>
                                    @Html.TextBoxFor(m => m.JobName, new { @class = "form-control", @readonly = "readonly", @id = "" })
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                <div class="form-group">
                                    <label>Minutes <span class="text-red-b">*</span></label>
                                    @Html.TextBoxFor(m => m.Minutes, new { @class = "form-control", required = "required", maxlength = "10", autocomplete = "off", @id = "" })
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                <div class="form-group">
                                    <label>Hours <span class="text-red-b">*</span></label>
                                    @Html.TextBoxFor(m => m.Hours, new { @class = "form-control required-auth", maxlength = "10", autocomplete = "off", @id = "" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                <div class="form-group">
                                    <label>Day of month <span class="text-red-b">*</span></label>
                                    @Html.TextBoxFor(m => m.DayofMonth, new { @class = "form-control", required = "required", maxlength = "10", autocomplete = "off", @id = "" })
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                <div class="form-group">
                                    <label>Month <span class="text-red-b">*</span></label>
                                    @Html.TextBoxFor(m => m.Month, new { @class = "form-control", required = "required", maxlength = "10", autocomplete = "off", @id = "" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                <div class="form-group">
                                    <label>Day of Week <span class="text-red-b">*</span></label>
                                    @Html.TextBoxFor(m => m.DayofWeek, new { @class = "form-control", required = "required", maxlength = "10", autocomplete = "off", @id = "" })
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                <div class="col-sm-12 checkbox-group">
                                    @Html.CheckBoxFor(m => m.JobEnable, new { @class = "form-check-input", @id = "JobEnable" })
                                    <label for="JobEnable" class="check-custom">Enable</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-md-12 col-sm-12 col-xs-12 p-0">
                        <div class="form-group" style="margin-bottom:5px;">
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12 p-0 text-center">
                                    <button type="submit" class="btn btn-main" style="margin-top:5px;">
                                        บันทึก
                                    </button>
                                    <button type="button" class="btn btn-gray" style="margin-top:5px;" data-dismiss="modal" aria-label="Close">
                                        ยกเลิก
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@*--------Modal Config---------*@

<script>
    function openModal(Id) {
        $('#ConfigModal').empty();
        $('#ConfigModal').load("@Url.Action("GetById", "Scheduler")/" + Id, function (response, status, xhr) {
            if (status === "success") {
                $('#ConfigModal').modal('show');
            }
        });
    }

    $(function () {
        $('.edit').on('click', function () {
            openModal($(this).data('id'));
        });

        if (@ViewBag.showPopUp == true) {
            $('#ConfigModal').modal('show');
        }
    });
</script>