CU/Controllers/FTPController.cs
using Microsoft.AspNetCore.Mvc;
using CU.Models;
using Microsoft.AspNetCore.Authorization;
using CU.Services;
using System.Linq;

namespace CU.Controllers
{
    [Authorize(Policy = Constants.PolicyName.FTPPage)]
    public class FTPController : BaseController
    {
        public IActionResult Index()
        {

            FTPService ftpServ = new FTPService();
            var ftpList = ftpServ.GetAllDefault();
            FTPDisplay gateway = ftpList.Where(f => f.type == (int)Constants.AppConstant.FtpServerType.Gateway).FirstOrDefault();
            if (gateway == null) gateway = new FTPDisplay((int)Constants.AppConstant.FtpServerType.Gateway);

            //FTPDisplay idm = ftpList.Where(f => f.type == (int)Constants.AppConstant.FtpServerType.IDM).FirstOrDefault();
            //if (idm == null) gateway = new FTPDisplay((int)Constants.AppConstant.FtpServerType.IDM);

            ViewBag.gateway = gateway;
           // ViewBag.idm = idm;

            ViewBag.showPopUp = "false";

            return View(new FTPDisplay());
        }

        public IActionResult GetById(string Id)
        {
            FTPService ftpServ = new FTPService();

            return PartialView("Detail", ftpServ.GetById(System.Convert.ToInt32(Id)));
        }

        [HttpPost]
        public ActionResult UpdateFTP(FTPDisplay model)
        {
            FTPService ftpServ = new FTPService();
            if(ModelState.IsValid)
            {
                if (ftpServ.Save(model)) return RedirectToAction("Index");
            }

            var ftpList = ftpServ.GetAllDefault();
            FTPDisplay gateway = ftpList.Where(f => f.type == (int)Constants.AppConstant.FtpServerType.Gateway).FirstOrDefault();
            if (gateway == null) gateway = new FTPDisplay((int)Constants.AppConstant.FtpServerType.Gateway);

            FTPDisplay idm = ftpList.Where(f => f.type == (int)Constants.AppConstant.FtpServerType.IDM).FirstOrDefault();
            if (idm == null) gateway = new FTPDisplay((int)Constants.AppConstant.FtpServerType.IDM);

            ViewBag.gateway = gateway;
            ViewBag.idm = idm;

            ViewBag.showPopUp = "true";
            return View("Index", model);
        }
    }
}

CU/Views/FTP/Detail.cshtml
@model CU.Models.FTPDisplay


@using (Html.BeginForm("UpdateFTP", "FTP", FormMethod.Post))
        {
            @Html.HiddenFor(m => m.id)
            <div class="modal-dialog modal-xl">
                <div class="modal-content">
                    <div class="modal-header" style="padding:12px 15px;">
                        <h4 class="modal-title">ตั้งค่า FTP SERVER</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <img src="~/Image/icon/cross-g.png" class="img-icon" />
                        </button>

                    </div>
                    <div class="modal-body">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                        <label>FTP Server Name <span class="text-red-b">*</span></label>
                                        @Html.TextBoxFor(m => m.serverip, new { @class = "form-control", required = "required" })
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                    <div class="form-group">
                                        <label>Port <span class="text-red-b">*</span></label>
                                        @Html.TextBoxFor(m => m.port, new { @class = "form-control", required = "required" })
                                    </div>
                                </div>
                            </div>

                            @if (Model.type == (int)CU.Constants.AppConstant.FtpServerType.IDM)
                            {
                                <div class="row">
                                    <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                        <div class="form-group">
                                            <label>Download Path <span class="text-red-b">*</span></label>
                                            @Html.TextBoxFor(m => m.DrivePath, new { @class = "form-control", required = "required" })
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                        <div class="form-group">
                                            <label>Upload Path <span class="text-red-b">*</span></label>
                                            @Html.TextBoxFor(m => m.PathUpload, new { @class = "form-control", required = "required" })
                                        </div>
                                    </div>
                                </div>
                            }

                            <div class="row">
                                <div class="col-md-4 col-sm-12 col-xs-12 clear-none">
                                    <div class="col-sm-12 checkbox-group">
                                        @Html.CheckBoxFor(m => m.isauthenticated, new { @class = "form-check-input", @id = "inputAuthentication" })
                                        <label for="inputAuthentication" class="check-custom">Authentication</label>
                                    </div>
                                </div>
                            </div>
                            <div id="requiredAuthentication">
                                <div class="row">
                                    <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                        <div class="form-group">
                                            <label>ชื่อผู้ใช้งาน <span class="text-red-b">*</span></label>
                                            @Html.TextBoxFor(m => m.username, new { @class = "form-control required-auth", @autocomplete = "new-user" })
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                        <div class="form-group">
                                            <label>รหัสผ่าน <span class="text-red-b">*</span></label>
                                            @Html.PasswordFor(m => m.password, new { @class = "form-control required-auth", @autocomplete = "new-password" })
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                        <div class="form-group">
                                            <label>ยืนยันรหัสผ่าน <span class="text-red-b">*</span></label>
                                            @Html.PasswordFor(m => m.confirmpassword, new { @class = "form-control required-auth", @autocomplete = "new-password" })
                                            @Html.ValidationMessageFor(m => m.confirmpassword, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="col-md-12 col-sm-12 col-xs-12 p-0">
                            <div class="form-group" style="margin-bottom:5px;">
                                <div class="row">
                                    <div class="col-md-12 col-sm-12 col-xs-12 p-0 text-center">
                                        <button id="" type="submit" class="btn btn-main" style="margin-top:5px;">
                                            บันทึก
                                        </button>
                                        <button id="" type="button" class="btn btn-gray" style="margin-top:5px;" data-dismiss="modal" aria-label="Close">
                                            ยกเลิก
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }

    @*--------.Modal Setting---------*@

    <script>
    function toggleRequiredAuth() {
        if ($('#inputAuthentication').prop("checked") == true) {
            $('.required-auth').prop('required', true);
            $('#requiredAuthentication').show();
        } else {
            $('.required-auth').prop('required', false);
            $('#requiredAuthentication').hide();
        }
    }

    $(function () {
        toggleRequiredAuth();


        $('#inputAuthentication').on('click', toggleRequiredAuth);
    });

    </script>

CU/Views/FTP/Index.cshtml
@model CU.Models.FTPDisplay
@{
    ViewData["Title"] = "FTP";

    FTPDisplay gateway = ViewBag.gateway;
}
@*@{ Layout = "_AuthorizeLayout"; }*@
<link rel="stylesheet" href="~/css/account.css" />
<link rel="stylesheet" href="~/css/global.css" />
<link rel="stylesheet" href="~/css/home.css" />

<div class="container">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="row flex-row">
            <div class="col-md-12 col-sm-12 col-xs-12 text-center head flex-row">
                <h1 class="mt-5 pb-0">FTP Server</h1> <br />
                                                 <h4 class="pt-0">CU Data Gateway</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 ftp">
                <div class="col-md-12 col-sm-12 col-xs-12 p-0 btn-setting row flex-row ">
                    <div class="btn-group mb-3">
                        @if (gateway.id != 0)
                        {
                            @*<a data-toggle="modal" data-target="#TestSmtpModal" class="btn btn-main hidden" id="divSend"><img src="~/Image/icon/email-w.png" class="img-icon" />&nbsp;ทดสอบส่ง</a>*@
                        }
                        <a href="@Url.Action("Index", "Admin")" class="secondary-btn">ย้อนกลับ</a>
                        <a class="primary-btn openmodel" data-id="@gateway.id"><span><img src="~/Image/icon/gear-w.png" class="img-icon">&nbsp;ตั้งค่า</span></a>
                        @*<a class="primary-btn" data-toggle="modal" data-target=".modal-setting"><span><img src="~/Image/icon/gear-w.png" class="img-icon">&nbsp;ตั้งค่า</span></a>*@
                    </div>
                </div>
                            <div class="col-md-11 col-sm-12 col-xs-12 smtp-group p-0" style="margin:0 auto 30px;">
                                @if (gateway.id == 0)
                                {
                                    <div id="divNoInfo"><h5 class="font-weight-bold">ไม่มีค่าพื้นฐาน</h5></div>
                                }
                                else
                                {
                                    <div class="col-md-12 col-sm-12 col-xs-12 p-0">
                                        <table width="100%" class="table table-condensed table-bordered">
                                            <tbody>
                                                <tr>
                                                    <td>FTP Server Name</td>
                                                    <td>@gateway.serverip</td>
                                                </tr>
                                                <tr>
                                                    <td>Port</td>
                                                    <td>@gateway.port</td>
                                                </tr>
                                                <tr>
                                                    <td class="">Authentication</td>
                                                    @if (gateway.isauthenticated)
                                                    {
                                                        <td><img src="~/Image/icon/tick-color.png" style="height:23px;"></td>
                                                    }
                                                    else
                                                    {
                                                        <td><img src="~/Image/icon/cross-color.png" style="height:23px;" /></td>
                                                    }
                                                </tr>
                                                @if (gateway.isauthenticated)
                                                {
                                                    <tr>
                                                        <td class="">ชื่อผู้ใช้งาน</td>
                                                        <td>@gateway.username</td>
                                                    </tr>
                                                }

                                            </tbody>
                                        </table>
                                    </div>
                                }
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            @*--------Modal Setting---------*@
            <div id="FTPModal" class="modal fade modal-setting" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">

            </div>
            @*--------.Modal Setting---------*@

            <script>
        $(function () {
        if (@ViewBag.showPopUp != null && @ViewBag.showPopUp == true) {
            $('#SmtpModal').modal('show');
        }
        });

        $('.openmodel').on('click', function () {
            openModal($(this).data('id'));
        });

        function openModal(Id) {
            $('#FTPModal').empty();
            $('#FTPModal').load("@Url.Action("GetById", "FTP")/" + Id, function (response, status, xhr) {
                if (status === "success") {
                    $('#FTPModal').modal('show');
                }
            });
        }
            </script>