CU/Controllers/SmtpController.cs
using CU.Constants;
using CU.Models;
using CU.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CU.Controllers
{
    [Authorize(Policy = PolicyName.SmtpPage)]
    public class SmtpController : BaseController
    {
        public IActionResult Index()
        {
            SmtpService smtpSetting = new SmtpService();
            ViewBag.showPopUp = "false";
            return View(smtpSetting.GetDefault());
        }

        [HttpPost]
        public IActionResult Update(SmtpDisplay input)
        {
            SmtpService smtpSetting = new SmtpService();
            if (ModelState.IsValid)
            {
                if (smtpSetting.Save(input)) return RedirectToAction("Index");
            }
            ViewBag.showPopUp = "true";
            return View("Index", input);
        }

        [HttpPost]
        public JsonResult TestSmtp(string ToEmail)
        {
            log.Info("testing smtp server to {0}", ToEmail);

            SmtpService smtpService = new SmtpService();
            if (smtpService.TestAsync(ToEmail) == "")
            {
                return Json(GetSuccess());
            }

            return Json(GetError());
        }

        public IActionResult MailTemplate()
        {
            SmtpService smtpSetting = new SmtpService();
            MailTemplateDisplay model = new MailTemplateDisplay();
            try
            {
                ViewBag.MailList = smtpSetting.GetMailTemplate();
                ViewBag.showPopUp = true;
                return View(model);
            }
            catch(Exception err)
            {
                log.Error(err.Message);
                return null;
            }
            
        }

        public ActionResult Create(MailTemplateDisplay model)
        {
            //MailTemplateDisplay model = new MailTemplateDisplay();
            try
            {
                SmtpService smtpSetting = new SmtpService();
                ViewBag.showPopUp = true;
                model.Id = Convert.ToInt32(UrlDecrypt(model.TemplateId));
                if (smtpSetting.SaveMailTemplate(model)) return RedirectToAction("MailTemplate");
            }
            catch(Exception err)
            {
                log.Error(err.Message, "Error Create MailTemplate");
                return null;
            }
            
            return RedirectToAction("MailTemplate");
        }
        
        public ActionResult ResetMail()
        {
            MailTemplateDisplay model = new MailTemplateDisplay();
            return PartialView("MailDetail", model);
        }

        public IActionResult GetMailById(string Id)
        {
            //CronJobService cronJobService = new CronJobService();
            SmtpService smtpSetting = new SmtpService();
            return PartialView("MailDetail", smtpSetting.GetMailTemplateById(Convert.ToInt32(UrlDecrypt(Id))));
        }
    }
}

CU/Views/Smtp/MailDetail.cshtml
@model CU.Models.MailTemplateDisplay

@using (Html.BeginForm("Create", "Smtp", FormMethod.Post))
{
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header" style="padding:12px 15px;">
                <h4 class="modal-title">ตั้งค่า Mail Template</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <img src="~/Image/icon/cross-g.png" class="img-icon" />
                </button>
            </div>
            <div class="modal-body">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    @Html.Hidden("TemplateId", CU.Utilities.CryptoHelpers.UrlEncrypt(Model.Id.ToString()))
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Key <span class="text-red-b">*</span></label>
                                @Html.TextBoxFor(m => m.MailKey, new { @class = "form-control", required = "required", autocomplete = "off", @id = "" })
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Mail Subject <span class="text-red-b">*</span></label>
                                @Html.TextBoxFor(m => m.MailSubject, new { @class = "form-control", required = "required", autocomplete = "off", @id = "" })
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Mail From <span class="text-red-b">*</span></label>
                                @Html.TextBoxFor(m => m.MailFrom, new { @class = "form-control", required = "required", autocomplete = "off", @id = "" })
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Mail To <span class="text-red-b">*</span></label>
                                @Html.TextBoxFor(m => m.MailTo, new { @class = "form-control required-auth", autocomplete = "off", @id = "" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Mail CC <span class="text-red-b">*</span></label>
                                @Html.TextBoxFor(m => m.MailCC, new { @class = "form-control", autocomplete = "off", @id = "" })
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="col-sm-12 checkbox-group">
                                @Html.CheckBoxFor(m => m.IsEnable, new { @class = "form-check-input", @id = "IsEnable" })
                                <label for="IsEnable" class="check-custom">Enable</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                            <div class="form-group">
                                <label>Mail Body <span class="text-red-b">*</span></label>
                                @Html.TextAreaFor(m => m.MailBody, new { @class = "form-control", @rows = "3", @cols = "20", @style = "min-height:70px;", id = "MailBody" })
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="col-md-12 col-sm-12 col-xs-12 p-0">
                    <div class="form-group" style="margin-bottom:5px;">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12 p-0 text-center">
                                <button type="submit" class="btn btn-main" style="margin-top:5px;">
                                    บันทึก
                                </button>
                                <button type="button" class="btn btn-gray" style="margin-top:5px;" data-dismiss="modal" aria-label="Close">
                                    ยกเลิก
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

CU/Views/Smtp/MailTemplate.cshtml
@model CU.Models.MailTemplateDisplay
@{
    ViewData["Title"] = "Mail Template";
}
@*@{ Layout = "_AuthorizeLayout"; }*@

<link rel="stylesheet" href="~/css/account.css" />

<div class="container body-page">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 text-center head">
                <h1>Mail Template</h1>
                <div class="btn-group"><a href="@Url.Action("Index", "Smtp")" class="btn btn-white">ย้อนกลับ</a></div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 form-frame csvset-page">
                <!--csv schedule config-->
                <button id="AddMailTemplate" data-toggle="modal" class="btn btn-main"><span><img src="~/Image/icon/add-w.png" class="img-icon" /> เพิ่ม MailTemplate</span></button>
                @using (Html.BeginForm("MailTemplate", "Smtp", FormMethod.Post, new { EncType = "multipart/form-data" }))
                {
                    <div class="col-md-12 col-sm-12 col-xs-12 search-result">
                        <div class="row">
                            <div class="table-frame-block">
                                <table cellpadding="0" cellspacing="0">
                                    <thead class="topic">
                                        <tr>
                                            <th class="topic-jobname">
                                                Job Mail
                                            </th>
                                            <th class="topic-fullname">
                                                From
                                            </th>
                                            <th class="topic-email">
                                                To
                                            </th>
                                            <th class="topic-enable">
                                                Status
                                            </th>
                                            <th class="topic-tools">
                                                &nbsp;
                                            </th>
                                        </tr>
                                    </thead>
                                    <thead class="topic topic-mobile">
                                        <tr>
                                            <th class="text-center">
                                                รายการ
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody class="detail detail-mobile">
                                        @foreach (var job in ViewBag.MailList)
                                        {
                                            <tr>
                                                <td class="detail-jobname">
                                                    @job.MailKey
                                                </td>
                                                <td class="detail-fullname">
                                                    @job.MailFrom
                                                </td>
                                                <td class="detail-email">
                                                    @job.MailTo
                                                </td>
                                                <td class="detail-enable">
                                                    <span class="text-topic">Enable:</span>
                                                    @if (job.IsEnable)
                                                    {
                                                        <img src="/Image/icon/tick-color.png" style="height:23px;">
                                                    }
                                                    else
                                                    {
                                                        <img src="/Image/icon/cross-color.png" style="height:23px;">
                                                    }
                                                </td>


                                                <td class="detail-tools">
                                                    <a class="btn-tools edit" data-id="@CU.Utilities.CryptoHelpers.UrlEncrypt(job.Id.ToString())"><img src="/Image/icon/edit-w.png" class="img-icon"></a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

@*--------Modal Config---------*@
<div id="ConfigModal" class="modal fade modal-setting" tabindex="-1" role="dialog" aria-labelledby="myModalLabel10" aria-hidden="true">
    @*@using (Html.BeginForm("Create", "Smtp", FormMethod.Post))
        {
            <div class="modal-dialog modal-xl">
                <div class="modal-content">
                    <div class="modal-header" style="padding:12px 15px;">
                        <h4 class="modal-title">ตั้งค่า Mail Template</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <img src="~/Image/icon/cross-g.png" class="img-icon" />
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            @Html.Hidden("Id", CUEnterprisePortal.Utilities.CryptoHelpers.UrlEncrypt(Model.Id.ToString()))
                            <div class="row">
                                    <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                        <div class="form-group">
                                            <label>Key <span class="text-red-b">*</span></label>
                                            @Html.TextBoxFor(m => m.MailKey, new { @class = "form-control", required = "required", autocomplete = "off", @id = "" })
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                        <div class="form-group">
                                            <label>Mail Subject <span class="text-red-b">*</span></label>
                                            @Html.TextBoxFor(m => m.MailSubject, new { @class = "form-control", required = "required", autocomplete = "off", @id = "" })
                                        </div>
                                    </div>

                                </div>

                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                    <div class="form-group">
                                        <label>Mail From <span class="text-red-b">*</span></label>
                                        @Html.TextBoxFor(m => m.MailFrom, new { @class = "form-control", required = "required", autocomplete = "off", @id = "" })
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                    <div class="form-group">
                                        <label>Mail To <span class="text-red-b">*</span></label>
                                        @Html.TextBoxFor(m => m.MailTo, new { @class = "form-control required-auth", autocomplete = "off", @id = "" })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                    <div class="form-group">
                                        <label>Mail CC <span class="text-red-b">*</span></label>
                                        @Html.TextBoxFor(m => m.MailCC, new { @class = "form-control", autocomplete = "off", @id = "" })
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                    <div class="col-sm-12 checkbox-group">
                                        @Html.CheckBoxFor(m => m.IsEnable, new { @class = "form-check-input", @id = "IsEnable" })
                                        <label for="IsEnable" class="check-custom">Enable</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-12 clear-none">
                                    <div class="form-group">
                                        <label>Mail Body <span class="text-red-b">*</span></label>
                                        @Html.TextAreaFor(m => m.MailBody, new { @class = "form-control", @rows = "3", @cols = "20", @style = "min-height:70px;", id = "MailBody" })
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="col-md-12 col-sm-12 col-xs-12 p-0">
                            <div class="form-group" style="margin-bottom:5px;">
                                <div class="row">
                                    <div class="col-md-12 col-sm-12 col-xs-12 p-0 text-center">
                                        <button type="submit" class="btn btn-main" style="margin-top:5px;">
                                            บันทึก
                                        </button>
                                        <button type="button" class="btn btn-gray" style="margin-top:5px;" data-dismiss="modal" aria-label="Close">
                                            ยกเลิก
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }*@
</div>
@*--------Modal Config---------*@

<script>
    function openModal(Id) {
        $('#ConfigModal').empty();
        $('#ConfigModal').load("@Url.Action("GetMailById", "Smtp")?Id=" + Id, function (response, status, xhr) {
            if (status === "success") {
                $('#ConfigModal').modal('show');
            }
        });
    }

    $(function () {
        $('.edit').on('click', function () {

            openModal($(this).data('id'));
        });

        $('#AddMailTemplate').on('click', function () {
          $('#ConfigModal').empty();
          $('#ConfigModal').load("@Url.Action("ResetMail", "Smtp")", function (response, status, xhr) {
            if (status === "success") {
                $('#ConfigModal').modal('show');
            }
        });

        });

        @*if (@ViewBag.showPopUp == true) {
            $('#ConfigModal').modal('show');
        }*@
    });
</script>